#!/bin/csh -f

set DEV_TOP = `pwd`

set TOUCH = ORIG
if ( ! -e configure.nps ) then
	touch configure.nps
	set TOUCH = TOUCH
endif

set nonomatch

set DIRS = ( dio     geogrid ungrib metgrid nemsinterp ungrib  ungrib   util     util      util        util        util    )
set EXES = ( diodump geogrid ungrib metgrid nemsinterp g1print g2print plotfmt plotgrids mod_levs rd_intermediate avg_tsfc )

set i = 1
foreach dir ( $DIRS )
	if ( -d $dir ) then 
		( cd $dir ; make -i DEV_TOP="${DEV_TOP}" TARGET="$EXES[$i].exe" clean )
	endif
	/bin/rm -f $EXES[$i].exe
	@ i ++
end

#	The nuclear option

find . -name \*.exe -exec \rm {} \; 
find . -name \*.o -exec \rm {} \; 
find . -name \*.mod -exec \rm {} \; 
find . -name \*.a -exec \rm {} \; 

#rm gmeta

#if ( -e GRIBFILE.AAA ) then
#	/bin/rm -f GRIBFILE.[A-Z][A-Z][A-Z]
#endif

#/bin/rm -f FILE:[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_[0-9][0-9] >& /dev/null

#if ( -e Vtable ) then
#	/bin/rm -f Vtable
#endif

#foreach core ( em nmm ) 
#	foreach io_form ( nc bin grib )
#		/bin/rm -f geo_${core}.d[0-9][0-9].${io_form} >& /dev/null
#		/bin/rm -f met_${core}.d[0-9][0-9].*.${io_form} >& /dev/null
#	end
#end

#if ( -e geogrid.log ) then
#	/bin/rm -f geogrid.log
#endif

#if ( -e metgrid.log ) then
#	/bin/rm -f metgrid.log
#endif

if ( "$1" == '-a' ) then
	/bin/rm -rf ./netcdf_links
	foreach dir ( $DIRS )
		if ( -d $dir ) then 
			( cd $dir ; make -i DEV_TOP="${DEV_TOP}" TARGET="${dir}.exe" superclean >& /dev/null )
		endif
		if ( -l ${dir}.exe ) then
			/bin/rm -f ${dir}.exe
		endif
	end
	if ( -e configure.nps ) then
		/bin/cp configure.nps configure.nps.backup
		/bin/rm -f configure.nps
	endif
endif

if ( ( $TOUCH == TOUCH ) && ( -e configure.nps ) ) then
	/bin/rm -f configure.nps
endif
