#!/bin/ksh
###############################################################
# Setup environment for the SREF Bias correction job - part II:
# bias estimation
#
# change log:
# 07/17/2007 Jun Du, initial implementation
# 08/04/2008 Jun Du, reduce 4 eta members and increase 2 nmm and 2 em members
#                    with proper model and member names
# 9/20/2009, Julia Zhu   Scripts are modified to be sharable
#                        between EMC and NCO
#         Please note that variable "RUN_ENVIR" is set and used
#         in the development enviroment only.
# 11/05/2010, Jun Du, Added precipitation bias correction job
# 11/02/2011, Jun Du, Modified to the 2012 new NMMB-based SREF (v6.0.0)
#                     by reducing grouping from 4 (Eta, RSM, NMM and ARW)
#                     to 3 (NMMB, NMM and ARW)
# 03/20/2019, Jun Du, Convert to Dell
###############################################################
set -xa

export OMP_NUM_THREADS=1
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us
export MP_MPILIB=mpich2
export MP_TASK_AFFINITY=core:1

#
# Specify whether the run is production or development
#
export RUN_ENVIR=${RUN_ENVIR:-nco}

#####################################################################################
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# DEV_SMS: If the job is to be running using ecFlow, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ecFlow script
then
  CONFIG_FILE=${CONFIG_FILE:-/gpfs/dell2/emc/modeling/noscrub/${LOGNAME}/sref.v7_dell/parm/sref_para_config_dell}
  . $CONFIG_FILE
  export userid=$LOGNAME
  export DATA_IN=${DATA_IN:-/gpfs/dell2/ptmp/$userid}
fi

echo `date` $0 `date -u` begin
export PS4='$SECONDS + '

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA_IN=${DATA_IN:-${DATAROOT}}

export DATA=$DATA_IN/${jobid:?}
rm -rf $DATA
mkdir -p $DATA

cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$DATA/jlogfile.${job}.$$}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=t${cyc}z 

###############################
# Specify NET and RUN name
##############################
export NET=sref
export RUN=sref

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFlow
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export VERBOSE=${VERBOSE:-YES}

export HOMEsref=${HOMEsref:-${NWROOT}/${NET}.${sref_ver}}
export EXECsref=${EXECsref:-$HOMEsref/exec}
export FIXsref=${FIXsref:-$HOMEsref/fix}
export PARMsref=${PARMsref:-$HOMEsref/parm}
export USHsref=${USHsref:-$HOMEsref/ush}

#export HOMEglobal=${HOMEglobal:-${NWROOTp1}}
#export EXECglobal=$HOMEglobal/exec
#export FIXglobal=$HOMEglobal/fix
#export PARMglobal=$HOMEglobal/parm
#export USHglobal=$HOMEglobal/ush

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

#############################################
# COMIN and COMOUT
#############################################
export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

export COMIN=${COMIN:-$COM_IN/${RUN}.${PDY}/${cyc}/pgrb}
export COMIN_ENSPRD=${COMIN_ENSPRD:-${COM_IN}/${RUN}.${PDY}/${cyc}/ensprod}

export COMOUT=${COMOUT:-$COM_OUT/${RUN}.${PDY}/${cyc}/pgrb_biasc}
export COMIN_BC=${COMIN_BC:-$COMOUT}
export COMOUT_BC=${COMOUT_BC:-$COM_OUT/${RUN}.${PDY}/${cyc}/ensprod_biasc}
export COMOUT_NDGD=${COMOUT_NDGD:-$COM_OUT/${RUN}.${PDY}/${cyc}/ensprod_ndgd}

export COMOUT_MISC=${COMOUT_MISC:-$COM_OUT/${RUN}.${PDY}/${cyc}/misc}
export COM_NDGD=${COM_NDGD:-$COM_IN/${RUN}.${PDY}/${cyc}/pgrb_ndgd}

mkdir -p -m 775 $COMOUT $COMOUT_BC $COMOUT_NDGD $COMOUT_MISC $COM_NDGD
 
env

#######################################################
# Pass information which is needed to run the Script
#######################################################
export ENDHOUR=87
export INCHOUR=03

export VERBOSE=YES

###################################################
# Execute the Script
###################################################
###################################################
# 1. Execute the bias correction Script of ensemble mean's precipitation (submit after enspost4special)
mkdir -m 775 $DATA/meanqpf_biasc
cd $DATA/meanqpf_biasc
export region=CONUS
$HOMEsref/scripts/exsref_qpfbiasestimate.sh.ecf mean

# 2. Execute the bias correction Script of individual members' precipitation (could submit after wrfpost)
mkdir -m 775 $DATA/qpf_biasc
cd $DATA/qpf_biasc
export region=CONUS
$HOMEsref/scripts/exsref_qpfbiasestimate.sh.ecf indiv

cat $DATA/qpf_biasc/$pgmout
cat $DATA/meanqpf_biasc/$pgmout

msg="JOB COMPLETED NORMALLY"
postmsg $jlogfile "$msg"

################################
# Remove the Working Directory
################################
cd $DATA_IN
if [ ${KEEPDATA:-NO} != YES ] ; then rm -rf $DATA ; fi

date
