#!/bin/ksh
#############################################################
# Setup environment for the SREF's downscaling job
#
# change log:
# 12/10/2011 Jun Du, initial implementation
#
#############################################################
set -xa
export PS4='$SECONDS + '

export OMP_NUM_THREADS=1
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us
export MP_MPILIB=mpich2
export MP_TASK_AFFINITY=core:1

#
# Specify whether the run is production or development
#
export RUN_ENVIR=${RUN_ENVIR:-nco}

#####################################################################################
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to ${DATAROOT}
# DEV_SMS: If the job is to be running using ecFlow, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to ${COMROOT}/$NET/${envir}
# COM_OUT: Directory for output file, default to ${COMROOT}/$NET/${envir}
# gespath: Directory for the guess or restart files, default to ${GESROOT}/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != nco ]      ### For Developers, "group_name" is passed from the ecFlow script
then
  CONFIG_FILE=${CONFIG_FILE:-/gpfs/dell2/emc/modeling/noscrub/${LOGNAME}/sref.v7_dell/parm/sref_para_config_dell}
  . $CONFIG_FILE
  export userid=$LOGNAME
  export DATA_IN=${DATA_IN:-/gpfs/dell2/ptmp/$userid}
fi

###############################################################
# This block can be modified for different test environment
###############################################################
if [ $RUN_ENVIR = nco -a $envir != prod ]; then
  export SENDDBN=${SENDDBN:-NO}
# export DBNROOT=${NWROOTp1}/spa_util/fakedbn
# export jlogfile=${jlogfile:-${COMROOT}/logs/${envir}/jlogfile}
fi

echo `date` $0 `date -u` begin

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA_IN=${DATA_IN:-${DATAROOT}}

#export DATA=$DATA_IN/${jobid:?}
export DATA=$DATA_IN/sref_downscaling_${CYC}_${envir}
rm -rf $DATA
mkdir -p $DATA

cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

###############################
# Specify NET and RUN name
##############################
export NET=sref
export RUN=sref

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFlow
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export VERBOSE=${VERBOSE:-YES}

export HOMEsref=${HOMEsref:-${NWROOT}/${NET}.${sref_ver}}
export EXECsref=${EXECsref:-$HOMEsref/exec}
export FIXsref=${FIXsref:-$HOMEsref/fix}
export PARMsref=${PARMsref:-$HOMEsref/parm}
export USHsref=${USHsref:-$HOMEsref/ush}

export HOMEglobal=${HOMEglobal:-${NWROOTp1}}
export EXECglobal=$HOMEglobal/exec
export FIXglobal=$HOMEglobal/fix
export PARMglobal=$HOMEglobal/parm
export USHglobal=$HOMEglobal/ush

# The grib_util module should be loaded prior to running this J-job
#module load grib_util

###################################
# Set up the UTILITIES
###################################
# Run setup to initialize working directory and utility scripts
## setup.sh  # no need, since using module load prod_util 

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

#############################################
# COMIN and COMOUT
#############################################
export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

export COMIN=$COM_IN/${RUN}.${PDY}/${cyc}/pgrb
export COM_NDGD=${COMOUT_NDGD:-$COM_IN/${RUN}.${PDY}/${cyc}/pgrb_ndgd}
export COMOUT_MISC=${COMOUT_MISC:-$COM_IN/${RUN}.${PDY}/${cyc}/misc}
export COMIN_BC=${COMIN_BC:-$COM_OUT/${RUN}.${PDY}/$cyc/pgrb_biasc}

export COMOUT=$COM_OUT/${RUN}.${PDY}/$cyc/pgrb_biasc
export COMOUT_BC=$COM_OUT/${RUN}.${PDY}/${cyc}/ensprod_biasc
export COMOUT_NDGD=$COM_OUT/${RUN}.${PDY}/${cyc}/ensprod_ndgd

export COMINnam=${COMINnam:-$(compath.py nam/prod)}

mkdir -p -m 775 ${COMOUT_NDGD} ${COM_NDGD} ${COMOUT_BC}
 
env

#######################################################
# Pass information which is needed to run the Script
#######################################################
export ENDHOUR=87
export INCHOUR=03

export VERBOSE=YES

###################################################
# Execute the Script
###################################################
# 1. Downscaling vector calculation
export COMINrtma=${COMINrtma:-$(compath.py rtma/prod)}
mkdir -m 775 $DATA/downscalevector
cd $DATA/downscalevector
## setup.sh  # no need, since using module load prod_util 
$HOMEsref/scripts/exsref_caldwnsvect.sh.ecf

# 2. Downscaling forecast (note: this job has to be run after Job 1 finishes!)
mkdir -m 775 $DATA/downscaleforecast
cd $DATA/downscaleforecast
## setup.sh  # no need, since using module load prod_util 
rm -rf $DATA/downscaleforecast/poescript

typeset -Z2 HR
HR=03
while [ $HR -le $ENDHOUR ]
do
 mkdir -m 775 $DATA/downscaleforecast/$HR
 echo "$HOMEsref/scripts/exsref_dwnsfcst.sh.ecf $HR > $DATA/downscaleforecast/${HR}.out " >>$DATA/downscaleforecast/poescript
 HR=`expr $HR + $INCHOUR`
done

chmod 775 $DATA/downscaleforecast/poescript
export MP_PGMMODEL=mpmd
export MP_CMDFILE=$DATA/downscaleforecast/poescript
#/usr/bin/poe -cmdfile $DATA/downscaleforecast/poescript -pgmmodel mpmd -ilevel 3 -labelio yes -stdoutmode ordered
#mpirun.lsf -cmdfile $DATA/downscaleforecast/poescript -pgmmodel mpmd -ilevel 3 -labelio yes -stdoutmode ordered
mpirun cfp $DATA/downscaleforecast/poescript

# 3. Ensemble product of downscaled forecasts (note: this job has to be run after Job 2 finishes!)
mkdir -m 775 $DATA/downscaleproduct
cd $DATA/downscaleproduct
## setup.sh  # no need, since using module load prod_util 
$HOMEsref/scripts/exsref_enspost_afterDS.sh.ecf 3hrly 197 111


########################################################
cat $pgmout

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

################################
# Remove the Working Directory
################################
cd $DATA_IN
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date
